### ISSUE TITLE
error in occ_data: related to data.table::rbindlist

### ISSUE THREAD

**Issue by ksanb** [ropensci/rgbif#428] opened 2020-09-02 16:28 UTC
I'm pretty new here, so I'd like to apologize for my ignorance in advance.

I'm having a problem with occ_data. Even in the simplest case, such as:
occ_data(scientificName = "Orthotrichum anomalum")

I get the following error:
Error in data.table::rbindlist(data, use.names = TRUE, fill = TRUE) : 
  Column 47 of item 1 is length 4 inconsistent with column 1 which is length 300. Only length-1 columns are recycled.

I also tried it on my spouse's computer to make sure there wasn't something strange going on with the packages I have installed, etc. She get's the same thing.

Thanks!

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgbif_3.2.0    ridigbio_0.3.5 taxize_0.9.97  dplyr_1.0.2   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.2    plyr_1.8.6        iterators_1.0.12 
 [6] tools_4.0.2       uuid_0.1-4        gtable_0.3.0      jsonlite_1.7.0    lifecycle_0.2.0  
[11] tibble_3.0.3      nlme_3.1-148      lattice_0.20-41   pkgconfig_2.0.3   rlang_0.4.7      
[16] foreach_1.5.0     cli_2.0.2         rstudioapi_0.11   crul_1.0.0        curl_4.3         
[21] parallel_4.0.2    httr_1.4.2        stringr_1.4.0     xml2_1.3.2        rgeos_0.5-3      
[26] generics_0.0.2    vctrs_0.3.4       grid_4.0.2        tidyselect_1.1.0  geoaxe_0.1.0     
[31] reshape_0.8.8     glue_1.4.2        httpcode_0.3.0    data.table_1.13.0 R6_2.4.1         
[36] oai_0.3.0         fansi_0.4.1       conditionz_0.1.0  sp_1.4-2          whisker_0.4      
[41] ggplot2_3.3.2     purrr_0.3.4       magrittr_1.5      scales_1.1.1      codetools_0.2-16 
[46] ellipsis_0.3.1    assertthat_0.2.1  bold_1.1.0        colorspace_1.4-1  ape_5.4-1        
[51] stringi_1.4.6     lazyeval_0.2.2    munsell_0.5.0     crayon_1.3.4      zoo_1.8-8

**Comment by sckott** [comment] 2020-09-02 18:33
thx for the report, having a look

**Comment by sckott** [comment] 2020-09-02 19:15
duplicate of #427 - follow that issue for resolution

**Closed by sckott** 2020-09-02 19:15 UTC
