### ISSUE TITLE
rgbif outage

### ISSUE THREAD

**Issue by damianooldoni** [ropensci/rgbif#415] opened 2020-06-23 15:36 UTC
It seems rgbif is experiencing an outage. @sckott , can you confirm it?

I get this error:

```r
> name_backbone(name = "Animalia")
 Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - 
This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). 
```

Same errors while using occurrence related functions, e.g. `occ_count(taxonKey = 1)`.

I asked to some colleagues to check it, they get same error.

<details> <summary><strong>Session Info</strong></summary>

```r
- Session info ----------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Europe/Paris                
 date     2020-06-23                  

- Packages --------------------------------------------------------------------------
 package     * version  date       lib source                         
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.1)                 
 backports     1.1.7    2020-05-13 [1] CRAN (R 3.6.3)                 
 broom         0.5.5    2020-02-29 [1] CRAN (R 3.6.3)                 
 callr         3.4.3    2020-03-28 [1] CRAN (R 3.6.3)                 
 cellranger    1.1.0    2016-07-27 [1] CRAN (R 3.6.1)                 
 cli           2.0.2    2020-02-28 [1] CRAN (R 3.6.3)                 
 clisymbols    1.2.0    2017-05-21 [1] CRAN (R 3.6.1)                 
 colorspace    1.4-1    2019-03-18 [1] CRAN (R 3.6.1)                 
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.1)                 
 crul          0.9.0    2019-11-06 [1] CRAN (R 3.6.1)                 
 curl          4.3      2019-12-02 [1] CRAN (R 3.6.3)                 
 data.table    1.12.8   2019-12-09 [1] CRAN (R 3.6.1)                 
 DBI           1.1.0    2019-12-15 [1] CRAN (R 3.6.3)                 
 dbplyr        1.4.2    2019-06-17 [1] CRAN (R 3.6.1)                 
 desc          1.2.0    2018-05-01 [1] CRAN (R 3.6.1)                 
 devtools      2.2.2    2020-02-17 [1] CRAN (R 3.6.3)                 
 digest        0.6.25   2020-02-23 [1] CRAN (R 3.6.3)                 
 dplyr       * 1.0.0    2020-05-29 [1] CRAN (R 3.6.3)                 
 ellipsis      0.3.1    2020-05-15 [1] CRAN (R 3.6.1)                 
 fansi         0.4.1    2020-01-08 [1] CRAN (R 3.6.1)                 
 forcats     * 0.5.0    2020-03-01 [1] CRAN (R 3.6.3)                 
 fortunes      1.5-4    2016-12-29 [1] CRAN (R 3.6.0)                 
 fs            1.3.2    2020-03-05 [1] CRAN (R 3.6.3)                 
 generics      0.0.2    2018-11-29 [1] CRAN (R 3.6.1)                 
 geoaxe        0.1.0    2016-02-19 [1] CRAN (R 3.6.1)                 
 ggplot2     * 3.3.1    2020-05-28 [1] CRAN (R 3.6.3)                 
 glue        * 1.4.1    2020-05-13 [1] CRAN (R 3.6.3)                 
 gtable        0.3.0    2019-03-25 [1] CRAN (R 3.6.1)                 
 haven         2.2.0    2019-11-08 [1] CRAN (R 3.6.1)                 
 here        * 0.1      2017-05-28 [1] CRAN (R 3.6.1)                 
 hms           0.5.3    2020-01-08 [1] CRAN (R 3.6.2)                 
 httpcode      0.3.0    2020-04-10 [1] CRAN (R 3.6.3)                 
 httr          1.4.1    2019-08-05 [1] CRAN (R 3.6.1)                 
 jsonlite      1.6.1    2020-02-02 [1] CRAN (R 3.6.3)                 
 knitr         1.28     2020-02-06 [1] CRAN (R 3.6.3)                 
 lattice       0.20-40  2020-02-19 [2] CRAN (R 3.6.3)                 
 lazyeval      0.2.2    2019-03-15 [1] CRAN (R 3.6.1)                 
 lifecycle     0.2.0    2020-03-06 [1] CRAN (R 3.6.3)                 
 lubridate     1.7.9    2020-06-08 [1] CRAN (R 3.6.3)                 
 magrittr      1.5      2014-11-22 [1] CRAN (R 3.6.1)                 
 memoise       1.1.0    2017-04-21 [1] CRAN (R 3.6.1)                 
 modelr        0.1.6    2020-02-22 [1] CRAN (R 3.6.3)                 
 munsell       0.5.0    2018-06-12 [1] CRAN (R 3.6.1)                 
 nlme          3.1-145  2020-03-04 [2] CRAN (R 3.6.3)                 
 oai           0.3.0    2019-09-07 [1] CRAN (R 3.6.1)                 
 pillar        1.4.4    2020-05-05 [1] CRAN (R 3.6.3)                 
 pkgbuild      1.0.8    2020-05-07 [1] CRAN (R 3.6.3)                 
 pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 3.6.1)                 
 pkgload       1.1.0    2020-05-29 [1] CRAN (R 3.6.3)                 
 plyr          1.8.6    2020-03-03 [1] CRAN (R 3.6.3)                 
 prettyunits   1.1.1    2020-01-24 [1] CRAN (R 3.6.3)                 
 processx      3.4.2    2020-02-09 [1] CRAN (R 3.6.3)                 
 ps            1.3.3    2020-05-08 [1] CRAN (R 3.6.3)                 
 purrr       * 0.3.4    2020-04-17 [1] CRAN (R 3.6.3)                 
 R6            2.4.1    2019-11-12 [1] CRAN (R 3.6.1)                 
 Rcpp          1.0.4.6  2020-04-09 [1] CRAN (R 3.6.3)                 
 readr       * 1.3.1    2018-12-21 [1] CRAN (R 3.6.1)                 
 readxl        1.3.1    2019-03-13 [1] CRAN (R 3.6.1)                 
 remotes       2.1.1    2020-02-15 [1] CRAN (R 3.6.3)                 
 reprex        0.3.0    2019-05-16 [1] CRAN (R 3.6.1)                 
 rgbif       * 2.3.0.91 2020-06-11 [1] Github (ropensci/rgbif@e97a50d)
 rgdal         1.5-10   2020-06-09 [1] CRAN (R 3.6.1)                 
 rgeos         0.5-3    2020-05-08 [1] CRAN (R 3.6.3)                 
 rlang         0.4.6    2020-05-02 [1] CRAN (R 3.6.3)                 
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.1)                 
 rstudioapi    0.11     2020-02-07 [1] CRAN (R 3.6.3)                 
 rvest         0.3.5    2019-11-08 [1] CRAN (R 3.6.1)                 
 scales        1.1.1    2020-05-11 [1] CRAN (R 3.6.3)                 
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.1)                 
 sp          * 1.4-2    2020-05-20 [1] CRAN (R 3.6.3)                 
 stringi       1.4.6    2020-02-17 [1] CRAN (R 3.6.2)                 
 stringr     * 1.4.0    2019-02-10 [1] CRAN (R 3.6.1)                 
 testthat      2.3.2    2020-03-02 [1] CRAN (R 3.6.3)                 
 tibble      * 3.0.1    2020-04-20 [1] CRAN (R 3.6.3)                 
 tidylog     * 1.0.0    2020-01-07 [1] CRAN (R 3.6.2)                 
 tidyr       * 1.1.0    2020-05-20 [1] CRAN (R 3.6.3)                 
 tidyselect    1.1.0    2020-05-11 [1] CRAN (R 3.6.3)                 
 tidyverse   * 1.3.0    2019-11-21 [1] CRAN (R 3.6.2)                 
 triebeard     0.3.0    2016-08-04 [1] CRAN (R 3.6.1)                 
 urltools      1.7.3    2019-04-14 [1] CRAN (R 3.6.1)                 
 usethis       1.5.1    2019-07-04 [1] CRAN (R 3.6.1)                 
 utf8          1.1.4    2018-05-24 [1] CRAN (R 3.6.1)                 
 vctrs         0.3.1    2020-06-05 [1] CRAN (R 3.6.1)                 
 whisker       0.4      2019-08-28 [1] CRAN (R 3.6.1)                 
 withr         2.2.0    2020-04-20 [1] CRAN (R 3.6.3)                 
 xfun          0.14     2020-05-20 [1] CRAN (R 3.6.3)                 
 xml2          1.3.2    2020-04-23 [1] CRAN (R 3.6.1)                 
 yaml          2.2.1    2020-02-01 [1] CRAN (R 3.6.2)
```
</details>

**Comment by sckott** [comment] 2020-06-23 15:42
i'm not getting the same result, that and other queries are working for me. did you try from another IP address?

**Comment by damianooldoni** [comment] 2020-06-23 15:48
Thanks. Due to Covid-19 we are all working at home, so at least three different IP addresses (min + two colleagues). But all in :belgium:

**Comment by sckott** [comment] 2020-06-23 15:50
just ran tests with the current version (v3) and the version you are on and all tests pass

Can you use the API in the browser? Do these links work?

https://api.gbif.org/v1/species?name=Puma%20concolor
https://api.gbif.org/v1/occurrence/search?taxonKey=1

**Comment by damianooldoni** [comment] 2020-06-23 15:52
Yes, API in browser works fine. Very strange.

**Comment by sckott** [comment] 2020-06-23 15:56
hmm, wonder if its the same problem as here? https://github.com/ropensci/rcrossref/issues/155

**Comment by hansvancalster** [comment] 2020-06-23 16:03
I am one of the colleagues of @damianooldoni and can confirm the same error on my machine (OS: Windows 7). 

<details><summary>session info</summary>
<p>

- Session info ---------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Dutch_Belgium.1252          
 ctype    Dutch_Belgium.1252          
 tz       Europe/Paris                
 date     2020-06-23                  

- Packages -------------------------------------------------------------------------------------
 package        * version date       lib source        
 abind            1.4-5   2016-07-21 [1] CRAN (R 4.0.0)
 assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports        1.1.6   2020-04-05 [1] CRAN (R 4.0.0)
 base64enc        0.1-3   2015-07-28 [1] CRAN (R 4.0.0)
 bayesplot        1.7.1   2019-12-01 [1] CRAN (R 4.0.0)
 bridgesampling   1.0-0   2020-02-26 [1] CRAN (R 4.0.0)
 brms           * 2.12.0  2020-02-23 [1] CRAN (R 4.0.0)
 Brobdingnag      1.2-6   2018-08-13 [1] CRAN (R 4.0.0)
 callr            3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
 cli              2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
 coda             0.19-3  2019-07-05 [1] CRAN (R 4.0.0)
 codetools        0.2-16  2018-12-24 [2] CRAN (R 4.0.0)
 colorspace       1.4-1   2019-03-18 [1] CRAN (R 4.0.0)
 colourpicker     1.0     2017-09-27 [1] CRAN (R 4.0.0)
 crayon           1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 crosstalk        1.1.0.1 2020-03-13 [1] CRAN (R 4.0.0)
 crul             0.9.0   2019-11-06 [1] CRAN (R 4.0.0)
 curl             4.3     2019-12-02 [1] CRAN (R 4.0.0)
 data.table       1.12.8  2019-12-09 [1] CRAN (R 4.0.0)
 desc             1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
 devtools         2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
 digest           0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
 dplyr            0.8.5   2020-03-07 [1] CRAN (R 4.0.0)
 DT               0.13    2020-03-23 [1] CRAN (R 4.0.0)
 dygraphs         1.1.1.6 2018-07-11 [1] CRAN (R 4.0.0)
 ellipsis         0.3.0   2019-09-20 [1] CRAN (R 4.0.0)
 fansi            0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 fastmap          1.0.1   2019-10-08 [1] CRAN (R 4.0.0)
 fortunes         1.5-4   2016-12-29 [1] CRAN (R 4.0.0)
 fs               1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
 geoaxe           0.1.0   2016-02-19 [1] CRAN (R 4.0.0)
 ggplot2          3.3.0   2020-03-05 [1] CRAN (R 4.0.0)
 ggridges         0.5.2   2020-01-12 [1] CRAN (R 4.0.0)
 glue             1.4.0   2020-04-03 [1] CRAN (R 4.0.0)
 gridExtra        2.3     2017-09-09 [1] CRAN (R 4.0.0)
 gtable           0.3.0   2019-03-25 [1] CRAN (R 4.0.0)
 gtools           3.8.2   2020-03-31 [1] CRAN (R 4.0.0)
 htmltools        0.4.0   2019-10-04 [1] CRAN (R 4.0.0)
 htmlwidgets      1.5.1   2019-10-08 [1] CRAN (R 4.0.0)
 httpcode         0.3.0   2020-04-10 [1] CRAN (R 4.0.0)
 httpuv           1.5.2   2019-09-11 [1] CRAN (R 4.0.0)
 httr             1.4.1   2019-08-05 [1] CRAN (R 4.0.0)
 igraph           1.2.5   2020-03-19 [1] CRAN (R 4.0.0)
 inline           0.3.15  2018-05-18 [1] CRAN (R 4.0.0)
 jsonlite         1.6.1   2020-02-02 [1] CRAN (R 4.0.0)
 later            1.0.0   2019-10-04 [1] CRAN (R 4.0.0)
 lattice          0.20-41 2020-04-02 [2] CRAN (R 4.0.0)
 lazyeval         0.2.2   2019-03-15 [1] CRAN (R 4.0.0)
 lifecycle        0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
 loo              2.2.0   2019-12-19 [1] CRAN (R 4.0.0)
 magrittr         1.5     2014-11-22 [1] CRAN (R 4.0.0)
 markdown         1.1     2019-08-07 [1] CRAN (R 4.0.0)
 Matrix           1.2-18  2019-11-27 [2] CRAN (R 4.0.0)
 matrixStats      0.56.0  2020-03-13 [1] CRAN (R 4.0.0)
 memoise          1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
 mime             0.9     2020-02-04 [1] CRAN (R 4.0.0)
 miniUI           0.1.1.1 2018-05-18 [1] CRAN (R 4.0.0)
 munsell          0.5.0   2018-06-12 [1] CRAN (R 4.0.0)
 mvtnorm          1.1-0   2020-02-24 [1] CRAN (R 4.0.0)
 nlme             3.1-147 2020-04-13 [1] CRAN (R 4.0.0)
 oai              0.3.0   2019-09-07 [1] CRAN (R 4.0.0)
 packrat          0.5.0   2018-11-14 [1] CRAN (R 4.0.0)
 pillar           1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
 pkgbuild         1.0.7   2020-04-25 [1] CRAN (R 4.0.0)
 pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
 pkgload          1.0.2   2018-10-29 [1] CRAN (R 4.0.0)
 plyr             1.8.6   2020-03-03 [1] CRAN (R 4.0.0)
 prettyunits      1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
 processx         3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
 promises         1.1.0   2019-10-04 [1] CRAN (R 4.0.0)
 ps               1.3.2   2020-02-13 [1] CRAN (R 4.0.0)
 purrr            0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
 R6               2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 Rcpp           * 1.0.4.6 2020-04-09 [1] CRAN (R 4.0.0)
 remotes          2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
 reshape2         1.4.4   2020-04-09 [1] CRAN (R 4.0.0)
 rgbif          * 2.2.0   2020-03-09 [1] CRAN (R 4.0.0)
 rgeos            0.5-2   2019-10-03 [1] CRAN (R 4.0.0)
 rlang            0.4.5   2020-03-01 [1] CRAN (R 4.0.0)
 rprojroot        1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
 rsconnect        0.8.16  2019-12-13 [1] CRAN (R 4.0.0)
 rstan            2.19.3  2020-02-11 [1] CRAN (R 4.0.0)
 rstantools       2.0.0   2019-09-15 [1] CRAN (R 4.0.0)
 rstudioapi       0.11    2020-02-07 [1] CRAN (R 4.0.0)
 scales           1.1.0   2019-11-18 [1] CRAN (R 4.0.0)
 sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
 shiny            1.4.0.2 2020-03-13 [1] CRAN (R 4.0.0)
 shinyjs          1.1     2020-01-13 [1] CRAN (R 4.0.0)
 shinystan        2.5.0   2018-05-01 [1] CRAN (R 4.0.0)
 shinythemes      1.1.2   2018-11-06 [1] CRAN (R 4.0.0)
 sp               1.4-1   2020-02-28 [1] CRAN (R 4.0.0)
 StanHeaders      2.19.2  2020-02-11 [1] CRAN (R 4.0.0)
 stringi          1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
 stringr          1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
 testthat         2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
 threejs          0.3.3   2020-01-21 [1] CRAN (R 4.0.0)
 tibble           3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
 tidyselect       1.0.0   2020-01-27 [1] CRAN (R 4.0.0)
 triebeard        0.3.0   2016-08-04 [1] CRAN (R 4.0.0)
 urltools         1.7.3   2019-04-14 [1] CRAN (R 4.0.0)
 usethis          1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
 vctrs            0.2.4   2020-03-10 [1] CRAN (R 4.0.0)
 whisker          0.4     2019-08-28 [1] CRAN (R 4.0.0)
 withr            2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
 xml2             1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
 xtable           1.8-4   2019-04-21 [1] CRAN (R 4.0.0)
 xts              0.12-0  2020-01-19 [1] CRAN (R 4.0.0)
 zoo              1.8-7   2020-01-10 [1] CRAN (R 4.0.0)

[1] C:/R/Library
[2] C:/Program Files/R/R-4.0.0/library

</p>
</details>

**Comment by sckott** [comment] 2020-06-23 16:30
thanks @hansvancalster 

Do you get the same problem if you upgrade to the latest version `install.packages("rgbif", repos = "https://dev.ropensci.org")`

**Comment by damianooldoni** [comment] 2020-06-23 20:03
I installed rgbif version 3.0.0.91 as @sckott asked and unfortunately I get same error :disappointed: 
@hansvancalster: do you confirm it?

I used `name_backbone` several times yesterday and everything worked fine, and I have not turned off my laptop last night, strange. And I did not installed any Windows update...

**Comment by sckott** [comment] 2020-06-23 20:50
checking on my windows VM (windows 10, don't have access to windows 7 that I know of). our CI https://github.com/ropensci/rgbif/runs/800772310?check_suite_focus=true tests on windows, but on windows server,

**Comment by sckott** [comment] 2020-06-23 21:09
what does `curl::curl_version()` give you

**Comment by sckott** [comment] 2020-06-23 21:11
I can't replicate the issue on windows 7

**Comment by hansvancalster** [comment] 2020-06-24 07:22
After updating

> I installed rgbif version 3.0.0.91 as @sckott asked and unfortunately I get same error 
> @hansvancalster: do you confirm it?

@damianooldoni @sckott yes I can confirm this on my laptop

**Comment by hansvancalster** [comment] 2020-06-24 07:24
@sckott :
> what does `curl::curl_version()` give you


$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps" 
[10] "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE

**Comment by damianooldoni** [comment] 2020-06-24 07:36
Hi @sckott : this is mine:

```r
> curl::curl_version()
$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps" 
[10] "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"   "smtp"   "smtps" 
[19] "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE
```

It seems the same of @hansvancalster.

**Comment by damianooldoni** [comment] 2020-06-24 08:21
Just asked to other rgbif users and this is what I got:
- Windows 10, curl version 7.64.1: OK
- Windows 10, curl version 7.59.0: OK

**Comment by damianooldoni** [comment] 2020-06-24 08:43
Another Windows 7 user gets same error. curl version almost the same as mine, only `libz_version` is slightly older (1.2.8). So, it is not that. See below.

<details> <summary><strong>curl version</strong></summary>
```r
curl::curl_version()

$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.8"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
[1] "dict" "file" "ftp" "ftps" "gopher" "http" "https" "imap" "imaps" "ldap" "ldaps" "pop3" "pop3s" "rtsp" "scp" "sftp"
[17] "smtp" "smtps" "telnet" "tftp"

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE
```

**Comment by milotictanja** [comment] 2020-06-24 09:27
I also tried on a Windows 7 and got the same error. 
<details>
<summary>session info</summary>
<br>

- Session info

 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Dutch_Belgium.1252          
 ctype    Dutch_Belgium.1252          
 tz       Europe/Berlin               
 date     2020-06-24                  

- Packages 
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
 backports     1.1.8   2020-06-17 [1] CRAN (R 4.0.1)
 callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
 cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 4.0.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
 crul          0.9.0   2019-11-06 [1] CRAN (R 4.0.0)
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.0)
 data.table    1.12.8  2019-12-09 [1] CRAN (R 4.0.0)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
 devtools      2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
 dplyr         1.0.0   2020-05-29 [1] CRAN (R 4.0.0)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
 fs            1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
 generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.0)
 geoaxe        0.1.0   2016-02-19 [1] CRAN (R 4.0.0)
 ggplot2       3.3.2   2020-06-19 [1] CRAN (R 4.0.2)
 glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.0)
 httpcode      0.3.0   2020-04-10 [1] CRAN (R 4.0.0)
 httr          1.4.1   2019-08-05 [1] CRAN (R 4.0.0)
 jsonlite      1.6.1   2020-02-02 [1] CRAN (R 4.0.0)
 lattice       0.20-41 2020-04-02 [2] CRAN (R 4.0.1)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 4.0.0)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.0)
 oai           0.3.0   2019-09-07 [1] CRAN (R 4.0.0)
 pillar        1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
 pkgbuild      1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
 plyr          1.8.6   2020-03-03 [1] CRAN (R 4.0.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
 processx      3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
 ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
 Rcpp          1.0.4.6 2020-04-09 [1] CRAN (R 4.0.0)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
 rgbif         2.3     2020-05-28 [1] CRAN (R 4.0.0)
 rgeos         0.5-3   2020-05-08 [1] CRAN (R 4.0.0)
 rlang         0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
 sp            1.4-2   2020-05-20 [1] CRAN (R 4.0.0)
 stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
 tibble        3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
 tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
 triebeard     0.3.0   2016-08-04 [1] CRAN (R 4.0.0)
 urltools      1.7.3   2019-04-14 [1] CRAN (R 4.0.0)
 usethis       1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
 vctrs         0.3.1   2020-06-05 [1] CRAN (R 4.0.1)
 whisker       0.4     2019-08-28 [1] CRAN (R 4.0.0)
 withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.0)
</details>

<details>
<summary>curl version</summary>
<br>
$version
[1] "7.64.1"

$ssl_version
[1] "(OpenSSL/1.1.1a) Schannel"

$libz_version
[1] "1.2.11"

$libssh_version
[1] "libssh2/1.8.2"

$libidn_version
[1] NA

$host
[1] "x86_64-w64-mingw32"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"    "sftp"  
[17] "smtp"   "smtps"  "telnet" "tftp"  

$ipv6
[1] TRUE

$http2
[1] FALSE

$idn
[1] TRUE
</details>

**Comment by damianooldoni** [comment] 2020-06-24 10:03
Thanks @milotictanja. I have just downgraded `curl` to the minimal requirement of rgbif 3.0.0, that is curl 3.3.

```r
devtools::install_version(package = "curl", version = "3.3", repos = "http://cran.us.r-project.org")
```
Then I reinstalled rgbif 3.0.0 but same error still occurs.

**Comment by sckott** [comment] 2020-06-24 16:52
Thanks all, we're looking into it

**Comment by jeroen** [comment] 2020-06-24 17:04
Hi, I can reproduce this. The server seems to be doing something unusual in the TLS handshake which breaks on Windows. I'll investigate this more closely, as a workaround maybe you can use the openssl backend, as described in [the vignette](
https://cran.r-project.org/web/packages/curl/vignettes/windows.html#multiple_ssl_backends)

**Comment by damianooldoni** [comment] 2020-06-24 20:12
This works, indeed. For any other Windows 7 user mentioned in this issue, the easiest way to do what @jeroen is speaking about in the [vignette](https://cran.r-project.org/web/packages/curl/vignettes/windows.html#multiple_ssl_backends) is to do the following:

1. Restart your R session
2. Open your `.Renviron` file. If you don't know where it is or you still don't have it one, just run `usethis::edit_r_environ()` (install `usethis` if you don't have it, it is worth, really)
3. Add `CURL_SSL_BACKEND=openssl` and save
4. Restart your R session twice (first time you could probably get an error message)
5. Everything should work fine. In particular, if you run `curl::curl_version` you should see this 

```r
$ssl_version
[1] "OpenSSL/1.1.1a (Schannel)"
```

It means you switched to OpenSSL (Schannel is now within brackets). Windows 7 by default is using Schannel.

Waiting for more in depth analysis, I think this is still a great workaround. :+1: Thanks a lot.

**Comment by jeroen** [comment] 2020-06-24 23:37
Looks like the gbif server may have enabled something on their server that doesn't work with older Windows versions. If you google for `SEC_E_ILLEGAL_MESSAGE` there are a lot of similar bug reports for other software.

 Some of those bug repots suggest that the problem is resolved by setting `SSLSessionTickets on` on the server. I guess you need to ask the gbif server admins if they have changed something on their server lately. @MattBlissett @timrobertson100

**Comment by damianooldoni** [comment] 2020-06-25 09:36
@MattBlissett: thanks a lot for the fast answer. I have tested it right now and it works fine. @hansvancalster , @milotictanja, can some of you confirm this? Just run a simple rgbif query  like `name_backbone("Plantae")`. Thanks a lot.

**Comment by hansvancalster** [comment] 2020-06-25 09:38
Works fine :+1:

**Comment by sckott** [comment] 2020-06-25 14:48
Thanks @damianooldoni for reporting this, @jeroen for figuring out the issue and @MattBlissett for making the fix. 

Yes, we can document this. This should be a Windows 7 and older issue, correct? Are there any other error messages users may see related to this TLS issue?

**Comment by jeroen** [comment] 2020-06-25 15:08
I think it's solved now, no documentation is needed.

**Comment by damianooldoni** [comment] 2020-06-25 15:18
Based on [@MattBlissett comment](https://github.com/ropensci/rgbif/issues/415#issuecomment-649348043) above, no documentation is needed, at least up to 2022. But this issue should be kept in mind in case other W7 (or older) related issues will occur.

**Comment by sckott** [comment] 2020-06-25 16:41
Okay, thanks.

**Closed by sckott** 2020-06-25 16:41 UTC
