### ISSUE TITLE
occ_download breaking for many species?

### ISSUE THREAD

**Issue by jresasco** [ropensci/rgbif#588] opened 2023-01-03 19:05 UTC
I'm trying to download gbif occurrences for 855 plants in a mountain range in Colorado, USA using occ_download in rgbif.

I get the following error and find that the dataset downloaded includes lots of occurrences outside of the defined extent. 

Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  HTTP/2 stream 3 was not closed cleanly before end of the underlying stream

Oddly the downloaded datasets work fine for a smaller list of species (I tried up to 201  species so far)

Is there a number of species or records at which the function breaks?

Here's the code:

# gbif taxon keys
gbif_taxon_keys = sort(unique(plants$key))

# study extent
geom = 'POLYGON((-106 38.4,-106 41,-104.7 41,-104.7 38.4,-106 38.4))'

queries = occ_download_prep(
    pred_in("taxonKey", gbif_taxon_keys),
    pred("hasCoordinate", TRUE),
    pred("hasGeospatialIssue", FALSE),
    pred_within(geom),
    user = user, pwd = pwd,
    email = email)
out_test = occ_download_queue(.list = list(queries))

**Comment by jhnwllr** [comment] 2023-01-04 15:44
I think the problem is likely to be with the polygon. 

You can see on the GBIF portal that the polygon is in the wrong direction (it's red). 

> Polygons must have anticlockwise ordering of points, or will give unpredictable results. (A clockwise polygon represents the opposite area: the Earth's surface with a 'hole' in it. Such queries are not supported.)

https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-106%2038.4,-106%2041,-104.7%2041,-104.7%2038.4,-106%2038.4))&occurrence_status=present

This slightly tweaked polygon is in the right "direction". 

https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-106%2038.4,-104.69093%2038.39255,-104.7%2041,-106%2041,-106%2038.4))&occurrence_status=present

This download worked for me. 

```r
occ_download(
pred_in("taxonKey", c(1,7)),
pred("hasCoordinate", TRUE),
pred("hasGeospatialIssue", FALSE),
pred_within('POLYGON((-106 38.4,-104.69093 38.39255,-104.7 41,-106 41,-106 38.4))'))
```

**Comment by jresasco** [comment] 2023-01-04 16:03
Thanks for your response, John. I subsequently caught the counter-clockwise issue with the polygon and fixed it after posting here. I'm not sure that was the problem because I still had the error popping up and the issue with the spurious records when I tried to download the data for my full species list (but the download worked correcltly for smaller subsets of the species list). I was able to get around the issue by downloading the data in batches of partial species lists. Attached is a list of the species if you'd like to try to recreate the error. But for practical purposes, my problem is solved 👍


[gbif_taxon_keys.csv](https://github.com/ropensci/rgbif/files/10345564/gbif_taxon_keys.csv)

**Comment by jhnwllr** [comment] 2023-01-05 12:34
I believe this user had the same error
https://github.com/ropensci/rgbif/issues/579

They used `curlopts=list(http_version=2)` to bypass the error. I have never ben able to reproduce the error. 

This comment says that 
> HTTP/2 stream 3 was not closed cleanly before end of the underlying stream

Is usually a server error, so probably isn't something that can be fixed in rgbif. 
https://github.com/jeroen/curl/issues/232#issuecomment-1160222277

That being said, I ran this download with no errors. 
https://www.gbif.org/occurrence/download/0238153-220831081235567

```r
library(rgbif)

gbif_taxon_keys = readr::read_csv("C:/Users/ftw712/Desktop/gbif_taxon_keys.csv") %>%
  pull(keys)

geom = "POLYGON((-106 38.4,-104.69093 38.39255,-104.7 41,-106 41,-106 38.4))"

queries = occ_download_prep(
  pred_in("taxonKey", gbif_taxon_keys),
  pred("hasCoordinate", TRUE),
  pred("hasGeospatialIssue", FALSE),
  pred_within(geom))
out_test = occ_download_queue(.list = list(queries))
```

**Closed** 2023-11-24 10:36 UTC
