### ISSUE TITLE
Long species list downloads via occ_download

### ISSUE THREAD

**Issue by jhnwllr** [ropensci/rgbif#362] opened 2019-07-12 13:39 UTC
Recently [see discussion here](https://discourse.gbif.org/t/downloading-and-citing-occurrence-data-for-multiple-taxa/1152), it has become possible to download **1000s of taxon keys** from GBIF via an http POST request. I recently made a successful test download using 9000 taxon keys: 

* [download with 9000 taxon keys](https://www.gbif.org/occurrence/download/0010219-190621201848488)

This can be done **because of use of the 'IN' predicate**. Because it saves space on the 12,000 character limit. 

```
 curl --include --user user:password --header "Content-Type: application/json" --data @file_9000.json http://api.gbif.org/v1/occurrence/download/request
```
Where **file_9000.json** looks like this but with MANY more taxon keys. 
```
{
"creator": "jwaller",
"notification_address": [
"jwaller@gbif.org"
],
"sendNotification": true,
"format": "SIMPLE_CSV",
"predicate": {
"type": "and",
"predicates": [
{
"type": "in",
"key": "TAXON_KEY",
"values": [1000003,
1000094,
___MANY MORE KEYS____
1000095,
1000096
]}
]}
}
```
I was wondering if the same thing would be possible to do with `rgbif::occ_download`? Since making the json file yourself is not ideal for most users. 

I tried to do the following but get a warning. 

```
library(rgbif)
occ_download("taxonKey = 2480946,5229208",body=NULL,type="in",format = "SIMPLE_CSV",user=user,pwd=pwd,email=email)
```

> Warning message: package 'rgbif' was built under R version 3.5.3  Error: Instantiation of [simple type, class org.gbif.api.model.occurrence.predicate.InPredicate] value failed: <key> may not be null Execution halted

Note: using `type=or` works fine. But this will send verbose json that will not be able to download anywhere near 9000 taxon keys. 

```
 '{
 "type": "or",
 "predicates": [
 {
 "type": "equals",
 "key": "TAXON_KEY",
 "value": "2480946"
 },
 {
"type": "equals",
 "key": "TAXON_KEY",
 "value": "5229208"
 }
 ]
 }'
```
Is there any way to get `rgbif::occ_download` to send json that looks like my file **file_9000.json** above using less characters?

**Comment by sckott** [comment] 2019-07-17 18:52
thanks @jhnwllr for this - sorry about delay, was on vacation. 

(this link https://www.gbif.org/occurrence/download/0010219-190621201848488 is not giving back the download info)

having a look now

**Comment by sckott** [comment] 2019-07-17 21:15
@jhnwllr fix pushed, reinstall from master. Should work now. The API docs have a slightly different JSON example from yours. Where the API docs have 

```json
"predicate": {
"type": "in",
...
```

using the `predicate` key and the value as a hash

Whereas you have

```json
"predicates": [
{
"type": "in",
```

using the `predicates` key and the value as an array

Does that different matter? Are both allowed with the "in" type?

**Comment by sckott** [comment] 2019-07-23 16:55
any thoughts @jhnwllr ?

**Comment by jhnwllr** [comment] 2019-07-24 13:28
hi @sckott, I have not been able to get to work. Even after the update. 

```
occ_download("taxonKey = 2480946,5229208",body=NULL,type="in",format = "SIMPLE_CSV",user=user,pwd=pwd,email=email)
```

> Error: Instantiation of [simple type, class org.gbif.api.model.occurrence.predicate.InPredicate] value failed: <key> may not be null
Execution halted

Apparently the 9000 taxon keys download is sort of an edge case that only works some of the time. So the reliable maximum is probably somewhat lower.

**Comment by sckott** [comment] 2019-07-24 17:12
thanks - i did have a question for you in https://github.com/ropensci/rgbif/issues/362#issuecomment-512571587 - any idaes?

**Comment by sckott** [comment] 2019-07-24 17:14
hmm, so you get that error on the `occ_download("taxonKey = 2480946,5229208",body=NULL,type="in",format = "SIMPLE_CSV",user=user,pwd=pwd,email=email)` example ? Or an example with 9000 taxon keys?  I assume the latter

**Comment by sckott** [comment] 2019-07-24 17:34
trying an example with 3100 taxon keys

```r
library(rgbif)
of <- seq(0, 3000, by = 100)
out <- list()
for (i in seq_along(of)) {
  out[[i]] <- name_suggest(rank = "species", limit=100, start = of[i])
}
df <- dplyr::bind_rows(out)
keys <- df$key
zz <- occ_download(sprintf("taxonKey = %s", paste0(keys, collapse = ",")), 
    type="in", format = "SIMPLE_CSV", curlopts = list(verbose = TRUE))
occ_download_meta(zz)
#> <<gbif download metadata>>
#>   Status: SUCCEEDED
#>   Format: SIMPLE_CSV
#>   Download key: 0016520-190621201848488
#>   Created: 2019-07-24T17:19:40.819+0000
#>   Modified: 2019-07-24T17:24:54.153+0000
#>   Download link: http://api.gbif.org/v1/occurrence/download/request/0016520-190621201848488.zip
#>   Total records: 0
#>   Request:
#>     type:  in
#>     predicates:
#>       > type: in, key: TAXON_KEY, value(s): 1000003,1000005,1000006,...
```

On Success, it says that there are 0 records - see API call https://api.gbif.org/v1/occurrence/download/0016520-190621201848488 - And there is a download to fetch, which has ~67K rows of data. Not sure what's going on there.

**Comment by jhnwllr** [comment] 2019-07-25 07:33
> thanks @jhnwllr for this - sorry about delay, was on vacation.
> 
> (this link https://www.gbif.org/occurrence/download/0010219-190621201848488 is not giving back the download info)
> 
> having a look now

I think this **9000-taxonkey download was deleted** because it does not work consistently.  Apparently the number of taxonkeys has to be somewhat less than 9000. The 8000 taxonkey download I did is still viewable: 
https://www.gbif.org/occurrence/download/0010212-190621201848488

There might also be other variables involved that I am not aware that affect the maximum number of taxonkeys the system can handle. In any case, **probably** 3000 or so will work consistently. With regards to the **0 total records**, it is apparently just a bug that needs to be fixed with these type of downloads. 

I will try your [example](https://github.com/ropensci/rgbif/issues/362#issuecomment-514727862) later to see if I can get it working.

**Comment by MattBlissett** [comment] 2019-07-25 07:47
> I think this 9000-taxonkey download was deleted because it does not work consistently.

We currently have a bug https://github.com/gbif/registry/issues/134 causing the Registry to overflow memory when retrieving some of these very long (≥ ~9000 taxa) queries. Please don't experiment with finding the limit on gbif.org, wait or use gbif-uat.org instead (John too!). I have had to temporarily block queries to John's example downloads.

`totalRecords` being 0 is recorded here: https://github.com/gbif/occurrence/issues/123 — increasing the limit for downloads exceeded a limit somewhere else. 

With https://github.com/gbif/occurrence/issues/49 we will determine what the limits are, and return an appropriate HTTP status (413 Payload Too Large) rather than accepting the request and having the download fail.  The limit might be different depending on the query, e.g. large polygons vs a huge disjunction.

**Comment by peterdesmet** [comment] 2019-07-26 08:53
Also pinging @damianooldoni on this issue, since we will use this functionality for [TrIAS](https://www.gbif.org/network/b153643d-735a-440f-a0e9-428b4f9d1cd2)

**Comment by sckott** [comment] 2019-07-27 01:10
Sounds good @MattBlissett - thanks for the info.

**Comment by MattBlissett** [comment] 2019-08-13 14:53
The limit is now 101,000 things, where every element in an "in" predicate counts as one, plus every other comparison predicate (equals, not, greaterThan etc). 

The intention is that that allows for 100,000 taxa/occurrenceIds/collectionCodes etc, and any other necessary filters for country/dataset etc.

Geometry WKTs are limited to 10,000 points.

Requests that are too large will be rejected immediately, with HTTP 413 Payload Too Large and an appropriate error message.

**Comment by sckott** [comment] 2019-08-13 16:03
thanks @MattBlissett ! saw the email as well

**Comment by jhnwllr** [comment] 2019-08-29 11:58
hi @sckott 

I was able to get `occ_download()` to work with `type="in"`, and [downloaded ~60,000 taxa using it](https://www.gbif.org/occurrence/download/0005623-190813142620410). 

If I try to use another parameter like `'hasGeospatialIssue = FALSE'` it fails...

# Fails
```
occ_download(
'taxonKey = 2977832,2977901,2977966,2977835',
'hasGeospatialIssue = FALSE',
type="in", format = "SIMPLE_CSV",user=user,pwd=pwd,email=email)
```
> Error: Instantiation of [simple type, class org.gbif.api.model.occurrence.predicate.InPredicate] value failed: <key> may not be null

With `type="and"` it works, but I will not be able to download large taxa lists with this type.

**Comment by sckott** [comment] 2019-08-30 17:33
thanks for the report @jhnwllr - having a look

**Comment by sckott** [comment] 2019-08-30 18:06
Hmm, I may need to rework how `occ_download` works since we're not currently allowing the user to specify the `type` for an individual predicate when there is more than one predicate (other than having the same type for all predicates, which isn't always the case). Will push a branch soon

**Comment by sckott** [comment] 2019-09-04 23:22
@jhnwllr if you have time, reinstall `remotes::install_github("ropensci/rgbif@downloads-rework")` - it's a reliatively big change in how you construct predicates, see examples https://github.com/ropensci/rgbif/blob/downloads-rework/R/occ_download.R#L141-L215 - instead of passing in a string like `"decimalLatitude > 50"`, which we parse internally, now you pass in each of those three parts into a function: `pred(decimalLatitude, 50, ">")` - and `pred_multi()` for composing predicates with multiple values combined with `or` or combined with `in` - In pygbif these methods are called other things, but I thought these names made more sense here

let me know any thoughts

**Comment by MattBlissett** [comment] 2019-09-05 07:10
I haven't tested it, but that looks like a useful improvement. Queries like this aren't very common, since they can't be made using the website, but if R supports them they probably would be more common.

In case it's helpful you can see this Java test class which has several examples of download predicates (it's then checking the generated SQL). I've highlighted the most complicated example: *Human or machine observations of animals or archea, in the UK or Ireland, observed in or before 1989 or in 2000*.

https://github.com/gbif/occurrence/blob/fdea92e0421706d756a4f91e5a4eba627842e7b7/occurrence-download/src/test/java/org/gbif/occurrence/download/query/HiveQueryVisitorTest.java#L57-L81

Avoiding the verbosity of Java, but keeping the same structure, that could be represented as 

```
and(
  in(BASIS_OF_RECORD, [MACHINE_OBSERVATION, HUMAN_OBSERVATION]),
  in(TAXON_KEY, [1, 2]),
  in(COUNTRY, [GB, IE]),
  or(
    lessThanEquals(YEAR, 1989),
    equals(YEAR, 2000)
  )
)
```
(The Java example uses a `DisjunctionPredicate` for the countries to test that the resulting SQL is the same as an `InPredicate`.)

Also, the definitive list of possible search terms is here: https://gbif.github.io/gbif-api/apidocs/org/gbif/api/model/occurrence/search/OccurrenceSearchParameter.html

**Comment by jhnwllr** [comment] 2019-09-05 07:37
hi thanks @sckott 

The examples work fine for me!

I was able to get my previous download attempt to work also:

```
remotes::install_github("ropensci/rgbif@downloads-rework")

library(rgbif)

occ_download(
pred_multi("taxonKey", c(2977832, 2977901, 2977966, 2977835), "in"),
pred("hasGeospatialIssue", "FALSE"),
format = "SIMPLE_CSV",
user=user,pwd=pwd,email=email)
```
> https://www.gbif.org/occurrence/download/0009769-190813142620410

I am working on a blog post about long species list downloads: 
https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/

I will add this method to the post if you think it is stable...

**Comment by MattBlissett** [comment] 2019-09-05 09:06
> _Human or machine observations of animals or archea, in the UK or Ireland, observed in or before 1989 or in 2000_.

With different ids (so as not to create unnecessary huge downloads), an example of this is here: https://www.gbif-uat.org/occurrence/download/0000222-190802075855554 / http://api.gbif-uat.org/v1/occurrence/download/0000222-190802075855554

**Comment by sckott** [comment] 2019-09-05 17:16
thanks very much @MattBlissett for the pointer to the Java examples, and for the simpler eg w/o Java verbosity. I'll see about doing the same tests here. And thanks for the enum link. And example of the query

**Comment by sckott** [comment] 2019-09-05 17:20
thanks for testing it @jhnwllr 

> I will add this method to the post if you think it is stable...

Not sure when you want to get the post out, but I want to add some more tests from the Java test suite, and do a bit more testing and asking other folks about the new user interface to make sure I'm not missing something - once I merge to master then i'd consider it stable - hopefully by tomorrow, maybe next monday

**Comment by sckott** [comment] 2019-10-22 01:51
@MattBlissett regarding this example 

> ```
> and(
>   in(BASIS_OF_RECORD, [MACHINE_OBSERVATION, HUMAN_OBSERVATION]),
>   in(TAXON_KEY, [1, 2]),
>   in(COUNTRY, [GB, IE]),
>   or(
>     lessThanEquals(YEAR, 1989),
>     equals(YEAR, 2000)
>   )
> )
> 
```

I'm tryint to support complicated queries like this. rgbif code looks like:

```r
occ_download_prep(
  pred_multi("basisOfRecord", c("MACHINE_OBSERVATION", "HUMAN_OBSERVATION"), "in"),
  pred_multi("taxonKey", c(9206251, 3112648), "in"),
  pred_multi("country", c("US", "MX"), "in"),
  preds(pred("year", 1989, ">="), pred("year", 1991, "<="), type = "or")
)
```

generating a request body that looks like

```json
{
  "creator": "sckott",
  "notification_address": ["myrmecocystus@gmail.com"],
  "format": "DWCA",
  "predicate": {
    "type": "and",
    "predicates": [
      {
        "type": "in",
        "key": "BASIS_OF_RECORD",
        "values": ["MACHINE_OBSERVATION", "HUMAN_OBSERVATION"]
      },
      {
        "type": "in",
        "key": "TAXON_KEY",
        "values": ["9206251", "3112648"]
      },
      {
        "type": "in",
        "key": "COUNTRY",
        "values": ["US", "MX"]
      },
      {
        "type": "or",
        "predicates": [
          {
            "type": "greaterThanOrEquals",
            "key": "YEAR",
            "value": "1989"
          },
          {
            "type": "lessThanOrEquals",
            "key": "YEAR",
            "value": "1991"
          }
        ]
      }
    ]
  }
}
```

Which succeeds https://www.gbif.org/occurrence/download/0026143-190918142434337 but I think the last set of paired predicates for year are ignored because in th result years are not limited to 1989 through 1991. I'm guessing I didn't set up the predicates correctly, but I don't see an example of how it should be done.

**Comment by sckott** [comment] 2019-10-28 17:27
any thoughts on the above @MattBlissett ?

**Comment by sckott** [comment] 2020-01-15 17:36
@MattBlissett any thoughts on https://github.com/ropensci/rgbif/issues/362#issuecomment-544776577 ?

**Comment by sckott** [comment] 2020-01-16 21:17
Downloads in `rgbif` (`occ_download` and friends) is undergoing an overhaul to support more complex queries and to properly support `in` queries which were are not currently supported. We'd love your feedback on the new download interface:

Install remotes::install_github("ropensci/rgbif@downloads-rework")

After installing, see `?occ_download` for examples and docs. 

Here's a brief example that should run quickly:

```r
library(rgbif)
```

construct predicates (`pred`, `pred_multi`, and `preds`) don't send the query to GBIF, they only construct a query statement.

```r
pred("taxonKey", 3119195)
pred("elevation", 5000, ">")
pred("geometry", "POLYGON((-14 42, 9 38, -7 26, -14 42))")
pred_multi("taxonKey", c(2977832, 2977901, 2977966, 2977835), "in")
pred_multi("basisOfRecord", c("MACHINE_OBSERVATION", "HUMAN_OBSERVATION"), "in")
preds(pred("year", 1989, "<="), pred("year", 2000, "="))
```

Pass predicates to `occ_download()` to run a download query

```r
occ_download(pred("taxonKey", 3119195), pred("elevation", 5000, ">"))
```

From here it works as before ...

**Comment by dnoesgaard** [comment] 2020-01-17 07:10
Hi @sckott, thanks for making these important improvements to the downloads query interface. Are you still waiting for comments from anyone from GBIF? I will happily chase them down :)

**Comment by MattBlissett** [comment] 2020-01-17 09:13
For object oriented languages, something like this would be more natural: 

```
pred("taxonKey", 3119195)
pred_gt("elevation", 5000)
pred("geometry", "POLYGON((-14 42, 9 38, -7 26, -14 42))")
pred_in("taxonKey", c(2977832, 2977901, 2977966, 2977835))
pred_in("basisOfRecord", c("MACHINE_OBSERVATION", "HUMAN_OBSERVATION"))
pred_or(pred_lte("year", 1989), pred("year", 2000))
```

but I don't use R, so this is an observation rather than a suggestion.

```
preds(pred("year", 1989, ">="), pred("year", 1991, "<="), type = "or")
```

This gives everything after 1989 *or* before 1991, which is all occurrences with any year at all.  You need an `and` query instead.

Other possibilities which aren't mentioned yet:
- an `or` or `and` query with more than 2 sub-predicates.
- `not` and `isNotNull`

**Comment by sckott** [comment] 2020-01-17 17:16
Thanks @dnoesgaard - just @MattBlissett and he did reply ✅ 

- Thanks for the idea about design. I'll have to think about that. Changing from e.g., `pred("elevation", 5000, ">")` to `pred_gt("elevation", 5000)`, may make it less easy to program with, i'll have a look at the change
- Thanks for the clarification on the year query - I should have seen that. 
- I'll show some examples with more than 2 sub-predicates
- I'll show some examples with `not` and `isNotNull`

**Comment by sckott** [comment] 2020-01-17 23:38
For anyone interested, on another branch (see [diff](https://github.com/ropensci/rgbif/compare/downloads-rework...download-predicate-dsl) from it to the main development branch with the downloads rework), the pred functions are redone to put the operators in the function names. 

install `remotes::install_github("ropensci/rgbif@download-predicate-dsl")`, then see `?download_predicate_dsl` for examples and docs - [quick link to the examples](https://github.com/ropensci/rgbif/blob/download-predicate-dsl/R/download_predicate_dsl.R#L80-L100)

cc @MattBlissett

**Comment by MattBlissett** [comment] 2020-01-20 15:55
The `pred_gt` etc is probably considered a better design by computer scientists, but the decision should be with the people who use R day-to-day, and run training courses, etc, and the maintainer who has to keep this working ;-)

(Maybe @laurarussell has an opinion? Between 

```R
pred("taxonKey", 3119195)
pred("elevation", 5000, ">")
pred("geometry", "POLYGON((-14 42, 9 38, -7 26, -14 42))")
pred_multi("taxonKey", c(2977832, 2977901, 2977966, 2977835), "in")
pred_multi("basisOfRecord", c("MACHINE_OBSERVATION", "HUMAN_OBSERVATION"), "in")
preds(pred("year", 1989, "<="), pred("year", 2000, "="), type = "or")
```
 
and 

```R
pred("taxonKey", 3119195)
pred_gt("elevation", 5000)
pred_within("geometry", "POLYGON((-14 42, 9 38, -7 26, -14 42))")
pred_in("taxonKey", c(2977832, 2977901, 2977966, 2977835))
pred_in("basisOfRecord", c("MACHINE_OBSERVATION", "HUMAN_OBSERVATION"))
pred_or(pred_lte("year", 1989), pred("year", 2000))
```

for creating a download in R.)

**Comment by sckott** [comment] 2020-01-20 16:10
thanks @MattBlissett for the comment - at least I prefer `pred_gt` over `pred(..., ">")`

**Comment by MattBlissett** [comment] 2020-01-21 17:42
> thanks @MattBlissett for the comment - at least I prefer `pred_gt` over `pred(..., ">")`

I say go with that then -- other colleagues at GBIF haven't shown a strong opinion.

**Comment by damianooldoni** [comment] 2020-01-22 08:21
As I work daily with scientists and as a R-user, I am pretty sure they would prefer `pred_gt` over `pred(..., ">")`.

**Comment by jhnwllr** [comment] 2020-01-22 08:55
Yes, I also have no strong preference. Probably a lot of worked examples would be the most helpful to users, and the interface doesn't matter that much. But for a complicated request pred_*() probably will be more readable.

**Comment by sckott** [comment] 2020-01-22 18:51
thanks @damianooldoni @jhnwllr for the feedback. 

more examples, will do

**Comment by sckott** [comment] 2020-01-25 06:18
merged to master

**Closed by sckott** 2020-01-25 06:18 UTC
Labels: downloads

**Comment by PLREY** [comment] 2020-10-22 21:00
Hi everyone, 
sorry to open this conversation...
I use only R and I try to use occ_download for 2082 sp (keys)
`keys<-sapply(splist, function(x) name_suggest(x)$data$key[1], USE.NAMES = FALSE) 
occ_download(
  pred_in("taxonKey", keys),
  pred("continent","europe"),
  format = "SIMPLE_CSV",
  user=user,pwd=pwd,email=email
)`

and I have this answer :
`Error: JSON parse error: Cannot construct instance of `org.gbif.api.model.occurrence.predicate.InPredicate`, problem: Invalid integer range: NULL; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.gbif.api.model.occurrence.predicate.InPredicate`, problem: Invalid integer range: NULL
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.gbif.api.model.occurrence.predicate.ConjunctionPredicate["predicates"]->java.util.ArrayList[0])`

I think the problem is the number of charachter or something like that, but I don't find a solution....
Can you help me @sckott  or others?
Thank you for your time, 

Pierre-louis Rey
_PhD student, Ecospat members, UNIL_

**Comment by sckott** [comment] 2020-10-26 23:14
thanks for question @PLREY Can you please share what is behind the `keys` variable. It should work as above there is discussion of even 60,000 or more working for the `IN` predicate.

**Comment by PLREY** [comment] 2020-10-27 07:39
Thanks for your time @sckott , `keys` correspond at a list containing more 2000 rows and for each row I have the key (with 7numbers) who identify the species on GBIF.
Maybe because it's a list..., if I transform the list into a data frame, do you think it's better?

In waiting your answer, I've stack the occurences for each species in a list with this method:

```
  n=nrow(tpl.na.30) 
  lim=100000
  spGBIF <- vector("list", n)
  
  for(i in 1:n) {
    spGBIF[[i]] = occ_search(taxonKey=keys[i], hasCoordinate=T, continent = 'europe', limit=lim)$data
    count=i
    print(count)
    }
```

**Comment by sckott** [comment] 2020-10-28 16:54
A list should work just fine, so I don't think that's the issue. 

Again, can you share at least a good portion of the keys so I can try to repliacte

**Comment by PLREY** [comment] 2020-10-29 15:52
Sorry, 
I didn't see we can deposit file
[keys.txt](https://github.com/ropensci/rgbif/files/5459624/keys.txt)

**Comment by sckott** [comment] 2020-10-30 19:08
I couldn't replicate the error using your keys.txt file. Perhaps there was an intermittent problem with GBIF services. Can you try it again?

**Comment by PLREY** [comment] 2020-11-03 10:12
Finally I find the mistake, 
it was necessary with the txt format to erase the "x" value and the "1 " with a subset and a gsub function.
I have now a list of chr values who run with the occ_download function.

All it's good, 
sorry for the disagreement, 
PL
